// File generated by FlutterFire CLI.

import 'firebase_options.dart';

// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyArsrILHkcPwK_wycXhIeLmwGuG-kDcYq0',
    appId: '1:903461278984:web:d0bfe95ed18845e06cc8bd',
    messagingSenderId: '903461278984',
    projectId: 'students-copy',
    authDomain: 'students-copy.firebaseapp.com',
    storageBucket: 'students-copy.appspot.com',
    measurementId: 'G-NLWW963T66',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAQCcoi8OJlPbwoHZ1ZJY1QuAdSo8smvW4',
    appId: '1:903461278984:android:ffeb3a5de86911646cc8bd',
    messagingSenderId: '903461278984',
    projectId: 'students-copy',
    storageBucket: 'students-copy.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBBaXzKslRIPceC381cEaj5Zg2ntNled6A',
    appId: '1:903461278984:ios:5d9f73ed3a4a7b476cc8bd',
    messagingSenderId: '903461278984',
    projectId: 'students-copy',
    storageBucket: 'students-copy.appspot.com',
    iosBundleId: 'com.example.studentscopy',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBBaXzKslRIPceC381cEaj5Zg2ntNled6A',
    appId: '1:903461278984:ios:5d9f73ed3a4a7b476cc8bd',
    messagingSenderId: '903461278984',
    projectId: 'students-copy',
    storageBucket: 'students-copy.appspot.com',
    iosBundleId: 'com.example.studentscopy',
  );
}
